<a href="https://colab.research.google.com/github/Ted-star7/Images/blob/main/Images_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import json
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Load dataset
file_path = '/content/drive/MyDrive/Dataset/Uzapoint_Master_Clean_Data.csv'
df = pd.read_csv(file_path)

# Preview dataset
df.head()

Mounted at /content/drive

,Product ID,Product Label,Clean_Product_Label,Category,Subcategory,Parent_Category,Category_norm,Subcategory_norm,Volume,Brand,Product Image,needs_review,has_image,data_quality_score
0,8782,Brown Belt,Brown Belt,ACCESSORIES,BELTS,Still_Other,accessories,belts,Unknown,BROWN,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
1,8783,Black Belt,Black Belt,ACCESSORIES,BELTS,Still_Other,accessories,belts,Unknown,BLACK,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
2,8785,Apple Watch 2020,Apple Watch 2020,ACCESSORIES,WATCHES,Still_Other,accessories,watches,Unknown,APPLE,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
3,8797,Apple Watch 2019,Apple Watch 2019,ACCESSORIES,WATCHES,Still_Other,accessories,watches,Unknown,APPLE,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
4,115430,ORAIMO TYPE C DATA CABLE,ORAIMO TYPE C DATA CABLE,ACCESSORIES,PHONE CHARGERS,Still_Other,accessories,phone chargers,Unknown,ORAIMO,NaN,True,False,Needs Review

In [2]:
image_df = df[['Product ID', 'Product Image']].copy()

image_df.head()

   Product ID                                      Product Image
0        8782  https://uzapointerp.uzahost.com/uploads/produc...
1        8783  https://uzapointerp.uzahost.com/uploads/produc...
2        8785  https://uzapointerp.uzahost.com/uploads/produc...
3        8797  https://uzapointerp.uzahost.com/uploads/produc...
4      115430                                                NaN

In [3]:
missing_mask = image_df['Product Image'].isna() | (image_df['Product Image'] == "")

missing_count = missing_mask.sum()
total_products = len(image_df)

print("Total Products:", total_products)
print("Missing Images:", missing_count)
print("Existing Images:", total_products - missing_count)

Total Products: 47944
Missing Images: 39967
Existing Images: 7977

In [4]:
missing_images_df = image_df[missing_mask]

missing_images_df.head()

   Product ID Product Image
4      115430           NaN
5      115431           NaN
6      115432           NaN
7      115433           NaN
8      119107           NaN

In [5]:
import pandas as pd
import os
from google.colab import drive

drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/Dataset/category_review_simple_20260303_195522/category_review_simple_20260303_195522"

import os
files = os.listdir(folder_path)

files

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

['Tobacco_simple.csv',
 'Non-Alcoholic_simple.csv',
 'Wines_simple.csv',
 'Others_simple.csv',
 'Beers_simple.csv',
 'Spirits_simple.csv']

In [6]:
import pandas as pd
import os

dfs = []

for file in files:

    path = os.path.join(folder_path, file)

    df_temp = pd.read_csv(path)

    dfs.append(df_temp)

combined_df = pd.concat(dfs, ignore_index=True)

combined_df.head()

   Product ID Category POS_Subcategory             Product Label
0      223308  Tobacco      Cigarettes               BIC LIGHTER
1      113125  Tobacco      Cigarettes  CIGAR DUNHILL DOUBLE PKT
2      113126  Tobacco      Cigarettes  CIGAR DUNHILL SINGLE PKT
3      113127  Tobacco      Cigarettes   CIGAR EMBASSY KINGS PKT
4      113128  Tobacco      Cigarettes              CIGAR SM PKT

In [7]:
print("Total Products:", len(combined_df))

Total Products: 47944

In [8]:
combined_df['Category'].value_counts()

Category
Spirits          21473
Wines             8502
Others            7556
Non-Alcoholic     5406
Beers             3984
Tobacco           1023
Name: count, dtype: int64

In [9]:
combined_df.to_csv(
"/content/drive/MyDrive/Dataset/Uzapoint_POS_Taxonomy_Base.csv",
index=False
)

In [11]:
combined_df['POS_Subcategory'].nunique()

52